### ISSUE TITLE
[calibration] Calibrate a RIG of cameras from an existing reconstruction using CCTAG

### ISSUE THREAD

**Issue by fabiencastan** [poparteu/openMVG#12]
Perform camera localization of multiple videos from an externally uncalibrated RIG and use this rigid contraint to calibrate the RIG. Each of the camera is internally (intrinsics) calibrated

* [x] Compute camera poses of N images sequences (depends on poparteu/openMVG#17)
* [x] Compute the rigid relative poses
* [x] Choose the best relative pose that minimize the reprojection error in all images
* [x] Bundle adjustment of all camera poses using the rigid relative pose constraint

Next is test results wrt GT #68

**Comment by fabiencastan** [comment]
1/ Create an initial reconstruction with openMVG
2/ Compute camera poses of N images sequences
3/ Compute the rigid relative poses
3a/ Choose the best relative pose that minimize the reprojection error in all images
3b/ Bundle adjustment of all camera poses to refine the ridig relative pose

**Comment by pmoulon** [comment]
You can also imagine to have a constraint over some relative motion during the BA.
Because you know that some relative motion must be equal between the poses Id.

**Comment by fabiencastan** [comment]
Yes, this is the idea of 3b. I updated my sentence to clarify the wording.

**Comment by fabiencastan** [comment]
@lcalvet What is the status of this task?
