### ISSUE TITLE
Conflict between options -f and -k in openMVG_main_SfMInit_ImageListing

### ISSUE THREAD

**Issue by caymard** [poparteu/openMVG#134]
When we set a value to the option `-k` (aka `--intrinsics`), the program throw an error:

> Cannot combine -f and -k options

This, even if we did not use the `-f` option (aka `--focal`).

Fix will be done in branch `popart_fix134`.

**Comment by simogasp** [comment]
It makes sense, you can provide either the focal length `-f` or the whole intrinsics `-k` which contain the focal length and the principal point. So it's not a bug, it's a feature.

**Comment by caymard** [comment]
It was fixed by @fcastan in 0c498f1c5141c47c005267d29c884a0b35f4b858. I did not saw it because I was working on my branch `popart_sfmstats`.

This [line](https://github.com/poparteu/openMVG/blob/0c498f1c5141c47c005267d29c884a0b35f4b858/src/software/SfM/main_SfMInit_ImageListing.cpp#L240) check if `userFocalLengthPixel != -1.0`, i.e the value by default if option `--focal` is not used. This way, no error anymore when you use `-k` and not `-f`.
