### ISSUE TITLE
Check usage of multiple camera models in the same reconstruction

### ISSUE THREAD

**Issue by fabiencastan** [poparteu/openMVG#143]
It doesn't work well on the first test but maybe due to the dataset.

- [ ] check matching
- [ ] check SfM

**Comment by simogasp** [comment]
Was it for Dallas? Can we close this?

**Comment by pmoulon** [comment]
Closing without feedback?

**Comment by fabiencastan** [comment]
Yes, I didn't manage to check that and it is no more a priority...
