### ISSUE TITLE
[alembic] jumpKeyframe() crashes if the very first frame is not localized

### ISSUE THREAD

**Issue by simogasp** [poparteu/openMVG#166]
Need to have some condition that prevents  `jumpKeyframe()` to crash when used for the first frame (ie there is no previous frame)

**Comment by simogasp** [comment]
@caymard any news?

**Comment by caymard** [comment]
Problem solved. Now if a frame is not localized:
- It is the frame 0 -> add default pose (`t=[0,0,0]` and `R=Indentity`)
- It is not -> use pose of previous frame

**Comment by caymard** [comment]
added in PR #188
