### ISSUE TITLE
[computeMatches] Crash with use_grid_sort=1

### ISSUE THREAD

**Issue by haavares** [poparteu/openMVG#169]
When running SIFT_CCTAG3 on the June11.01 dataset, openMVG_main_ComputeMatches crashes when --use_grid_sort is 1. This is the default in scriptMvg.

Please find attached a backtrace from the segfault.

[grid-sort-bug.txt](https://github.com/poparteu/openMVG/files/325605/grid-sort-bug.txt)

**Comment by fabiencastan** [comment]
Do you mean that with `--use_grid_sort 0` it works fine?

**Comment by haavares** [comment]
Yes

**Comment by fabiencastan** [comment]
Fixed here:
https://github.com/poparteu/openMVG/commit/9eb78d99ff448336d425e0de5369295868399c7d
