### ISSUE TITLE
Resectioning with auto-calibration

### ISSUE THREAD

**Issue by fabiencastan** [poparteu/openMVG#18]
Estimate intrinsics directly in the resectioning.

Currently, we need an initial guess of the focal length and we refine all instrinsics in the Bundle Adjustment.

**Comment by pmoulon** [comment]
This is an existing feature: https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/pipelines/sequential/sequential_SfM.cpp#L819

**Comment by pmoulon** [comment]
Some views can have no intrinsic defined at the start.
the field id_intrinsic will be filled with the value of UndefinedIndexT automatically if no sensor size have been found for the image.
