### ISSUE TITLE
Alembic exporter

### ISSUE THREAD

**Issue by fabiencastan** [poparteu/openMVG#2]
Need poparteu/openMVG#14
Todo:
- [x] Create an exporter class inside the library
- [x] Visibility list
- [x] Index for views, poses, intrinsics
- [ ] Use real sensor width (if exists)

**Comment by fcastan** [comment]
Image planes are missing

**Comment by caymard** [comment]
add some todos in description

**Comment by pmoulon** [comment]
Closed even the real sensor size is not used?

**Comment by fabiencastan** [comment]
Yes, you're right. I close this one as it is working and it is not a blocking step for a first release. I just create a new one for the next sprint.
