### ISSUE TITLE
Bug in sfm/utils/alignment.hpp - applyTransform - also control points must be transformed

### ISSUE THREAD

**Issue by zvrba** [poparteu/openMVG#207]
The code is as follows:

```
  for(auto& view: sfmData.views)
  {
    geometry::Pose3& pose = sfmData.poses[view.second->id_pose];
    pose = pose.transformSRt(S, R, t);
  }
```

If the same pose is referenced by multiple views, it will be transformed multiple times, leading to incorrect end result.

**Comment by simogasp** [comment]
not a bug, there is no shared poses

**Comment by simogasp** [comment]
the real bug is that the control points are not transformed

**Comment by pmoulon** [comment]
The best would be to use openMVG::sfm::ApplySimilaritythat will do the job
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_data_transform.hpp#L23

**Comment by simogasp** [comment]
great more duplicated code... :-)
And with the same bug... the control points should be transformed as well, shouldn't they?

**Comment by pmoulon** [comment]
Yes ControlPoints was not transformed, since they are often linked to a static SRS (Spatial Reference System).As discussed in another thread, an option will come in a future update to make the control point transformed or not.

**Comment by simogasp** [comment]
ok i added the boolean. 
I think we added the same function at almost the same time :-)
