### ISSUE TITLE
Tests with ground truth on travis

### ISSUE THREAD

**Issue by fabiencastan** [poparteu/openMVG#23]
- [x] add the ground truth test
- [x] change to incremental pipeline
 - how to choose the A/B pair ? -> automatic
- [ ] perform quality evaluation (ratio ? time ?)
 - [ ] caymard/SfM_quality_evaluation#1
- [ ] reduce time by using travis cache

**Comment by caymard** [comment]
It seems that puting in cache caymard/SfM_quality_evaluation is making trouble. The cache part exits with this error : 
`running 'casher push' took longer than 180 seconds and has been aborted`

**Comment by fabiencastan** [comment]
Could be closed?

**Comment by caymard** [comment]
No, there's a little bug to fix for the cache process
