### ISSUE TITLE
Find correct parameters for onset usage

### ISSUE THREAD

**Issue by fabiencastan** [poparteu/openMVG#24]
Like ~100 images in less than 15 minutes for SfM without losing too many cameras

Linked to http://github.com/poparteu/openMVG/issues/22

**Comment by pmoulon** [comment]
Can be done by using downsized images?

**Comment by fabiencastan** [comment]
With the grid on features extraction and matching as well as image matching based on voctree and performance improvements of SfM, we have usable timings.
