### ISSUE TITLE
openMVG_main_IncrementalSfM crashes

### ISSUE THREAD

**Issue by zvrba** [poparteu/openMVG#261]
In `sequential_SfM.cpp`, function `ComputeTracksLengthsHistogram`, at following line: `*histo = Histogram<double>(dMin, dMax, dMax-dMin+1);`

`vec_nbTracks` is empty, so `minMaxMeanMedian` leaves `dMin`, `dMax`, etc. uninitialized. `dMin` happens to be `NaN` so `nBins` parameter to `Histogram<double>::Histogram` gets converted to a meaningless integer  leading to

```
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_fill_insert
```

**Comment by simogasp** [comment]
we should add at the beginning of the function `ComputeTracksLengthsHistogram`

```c++
if(_sfm_data.GetLandmarks().empty())
{
  OPENMVG_LOG_WARNING("Impossible to compute the track length histogram, no tracks found")
  return 0;  // or -1.0, ComputeResidualsHistogram() is similar and returns -1 if it fails
}
```

Also, maybe, we should not call the functions at all if we know that the reconstruction did not work.
