### ISSUE TITLE
Color as an option of file format conversion

### ISSUE THREAD

**Issue by fabiencastan** [poparteu/openMVG#33]
- [x] Merge ComputeSfM_DataColor into an option of ConvertSfM_DataFormat.
- [x] export point colors in ABC

**Comment by simogasp** [comment]
@fabiencastan 
* The first item should have been done in poparteu/openMVG##153
* The second item has been done in 55349b5 but now I think we have the issue discussed in https://github.com/mikrosimage/mayaMVG/issues/165#issuecomment-225180550 . But maybe we can close this and open another one to fix the abc

**Comment by fabiencastan** [comment]
yes
