### ISSUE TITLE
ABC export finishing

### ISSUE THREAD

**Issue by fabiencastan** [poparteu/openMVG#34]
- [x] use the correct sensor size if available
- [x] export visibility
- [x] create a global transform and a transform for all cameras to have a nice hierarchy
- [x] add prefix for all custom properties (and maybe better names)
- [x] name pointCloud as "mvgPointCloud"
- [x] check compatibility export/import

In the continuity of https://github.com/poparteu/openMVG/issues/2

**Comment by eprana** [comment]
I need to have the visibility information on the points. 
I added --OBSERVATIONS option to the alembic export command, but I can't see the attribute on point cloud. 
The .abc file is heavier.
