### ISSUE TITLE
Test GT Levallois dataset

### ISSUE THREAD

**Issue by fabiencastan** [poparteu/openMVG#35]
- [ ] Script to set custom attributes in Maya
- [x] Export ABC with reconstructed cameras
- [x] Export ABC with virtual camera motion
- [x] Add sfmdata in input of evalQuality (--gt)
https://github.com/poparteu/openMVG/blob/alembic_io/src/software/SfM/main_evalQuality.cpp#L88
"--gt": Can be a folder (as currently) or a standard sfmdata file
- [x] Support missing cameras
https://github.com/poparteu/openMVG/blob/alembic_io/src/software/SfM/main_evalQuality.cpp#L129
We print the number of reconstructed cameras and compare the reconstructed ones (based on their ID).

- [x] Create test for reconstruction
- [x] Create test for camera localization
- [x] Create a dedicated github repository with the data

**Comment by fabiencastan** [comment]
What is the status of this task?

**Comment by caymard** [comment]
You have the relocalization test script on my github. It needs some finishing touches but the main work is there.

**Comment by fabiencastan** [comment]
Could you check the checkboxes and clean the description of the task if not up-to-date?
