### ISSUE TITLE
Add vocabulary tree

### ISSUE THREAD

**Issue by fabiencastan** [poparteu/openMVG#4]
* [X] add the main classes
* [x] reimplement/port readFeatures, possibly using automatic switching desc/desc.zip
	* careful with loading char/float
	* decide what to load: so far it expects eigen float features as output object
	* it should work with a simple list.txt with the name of the .desc to load as well as a sfm_data to create the voctree from a openmvg dataset
* [x] port the essential apps
   * [X] createvoctree
   * [X] pairlistFromVocTree
   * [x] testvoctree
* [x] code style: spaces et al
* [x] CAREFULLY update/merge with a more recent develop (@fabiencastan)

**Comment by fabiencastan** [comment]
Could be closed?

**Comment by simogasp** [comment]
Still have to port the unity tests for kmeans &C
