### ISSUE TITLE
ComputeMatches does not save the matches.f.txt

### ISSUE THREAD

**Issue by simogasp** [poparteu/openMVG#40]
The file is created but it's always empty. There must be a bug of some sort in `ExportPairedIndMatchFile`
The other function `ExportPairedIndMatchFilePerImage` works, instead.

**Comment by fabiencastan** [comment]
You may need to merge with dev_mikros.
This was fixed in https://github.com/poparteu/openMVG/commit/abf4c47e005f46c6dd21270ca35f8c7a183cabc4
