### ISSUE TITLE
Camera Localization inside an existing reconstruction

### ISSUE THREAD

**Issue by fabiencastan** [poparteu/openMVG#5]
Close to the incremental method, but do not modify the 3D reconstruction (cameras & 3D points).
* [x] low level api for
  * [x] matching
  * [x] resection
* [x] bundle adjustment for a single camera after resection
* [x] port the class from cameraLocalization

**Comment by simogasp** [comment]
really?

**Comment by fabiencastan** [comment]
Yes, camera localization could be a subject for 1 year of work... but the first version is done.
Could you add new tasks for the next steps?
