### ISSUE TITLE
[Parameters] Two different sets of parameters for natural or cctag features.

### ISSUE THREAD

**Issue by lcalvet** [poparteu/openMVG#50]
Create a class of parameters used both in the SfM and the camera localizsation:
This class should hold all the thresholds (usually hardcoded) in all the function. 

This set of parameters MUST BE different depending whether natural or artificial features are used. This mainly comes from the fact that the artificial features ensure a better accuracy compared to the natural ones but are much less sparse in the reconstruction.

**Comment by simogasp** [comment]
remove all the `HAVE_CCTAG`

**Comment by fabiencastan** [comment]
This is solved by computeCCTagStructureFromKnownPoses.
