### ISSUE TITLE
[travis] cache Ceres

### ISSUE THREAD

**Issue by simogasp** [poparteu/openMVG#51]
Make travis compile the repository using a cached copy of Ceres. It will speed up a lot (50%) the compilation time

**Comment by fabiencastan** [comment]
Status?

**Comment by caymard** [comment]
@fcastan Not started. Probably finished today.

**Comment by fabiencastan** [comment]
Status?

**Comment by caymard** [comment]
Some problems with ceres dependencies on travis. Waiting for travis staff reponse.

**Comment by pmoulon** [comment]
Which are the dependencies that create problems?
I see that you want to enable suitesparse & cxsparse backend for ceres.
You can start by just enabling cxsparse and then handle and add suitesparse.

**Comment by caymard** [comment]
cxsparse is the [problem](https://travis-ci.org/poparteu/openMVG/builds/102140510#L133)

**Comment by pmoulon** [comment]
Why not consider this version: https://github.com/TheFrenchLeaf/CXSparse
BTW, if you have already set the SuiteSparse backend you can ignore to set the cxsparse backend.

As you see here, OpenMVG has already a mechanism that will try to use the best Sparse backend of Ceres if it is avaible:
https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/sfm_data_BA_ceres.cpp#L63

**Comment by pmoulon** [comment]
Moreover, does cxsparse is not already included in the SuiteSparse that your are installing:
https://github.com/PetterS/SuiteSparse/tree/master/CXSparse

**Comment by caymard** [comment]
Note for myself : 
/!\ USE WITH PRECAUTIONS /!\
```bash
git commit --amend
git push --force
```
/!\ USE WITH PRECAUTIONS /!\

**Comment by pmoulon** [comment]
General note: you can make the "force" only on a branch to limit the risk to kill the history of the other branch if you have also done modification...
