### ISSUE TITLE
[sfm] Use simultaneously sift and cctag features.

### ISSUE THREAD

**Issue by lcalvet** [poparteu/openMVG#53]
Be able to use both natural regions and CCTag regions in the entire SfM pipeline.
* [x] create a class `SIFT_CCTAG_Image_describer` that transparently uses the two feature extractors [3a55b1e4062f62e2837bf5a8e4cecc1d607cfc25]
* [x] when matching features use brute force or FLANN rather than the default method
* [x] it would be nice to have #50 as CCTag have high rejection rate

**Comment by fabiencastan** [comment]
Could be closed, no?

Using brute force or flann is a recommandation. Nothing to implement.
Change thresholds to reduce rejections is another task.

**Comment by simogasp** [comment]
Yes it's more a reminder of the issues that we have to tackle when reconstructing the scene with cctag. For the moment no more implementations are needed
