### ISSUE TITLE
[alembic] export animated cameras

### ISSUE THREAD

**Issue by simogasp** [poparteu/openMVG#56]
Currently cameras are exported individually.
A nice feature would be to have rather an animated camera. This is better if for example we want to export the movement of the camera rig, so we have just 3 cameras moving around and not 3 series of cameras
it goes with #2 and #34

**Comment by pmoulon** [comment]
Neat idea.
Could be an option for camera rig (export contiguous camera/pose indexes as an animated camera)

**Comment by fabiencastan** [comment]
Could be closed?

**Comment by caymard** [comment]
Will be closed when PR #84 is merged
