### ISSUE TITLE
Add an option in the imageListing to generate a UID for the cameras

### ISSUE THREAD

**Issue by fabiencastan** [poparteu/openMVG#6]

**Comment by pmoulon** [comment]
based on MD5?

**Comment by fabiencastan** [comment]
2 solutions:
1) hash of the metadatas (contains shooting time + UID of the camera device)
2) md5 of the image file directly

Not sure what is the best.

**Comment by pmoulon** [comment]
I understand, not easy to defined.
TIMESTAMP_UIDCam_X can be good.
Ability to retrieve the timestamp and the used camera.
