### ISSUE TITLE
[localization] Camera rig localization with natural features

### ISSUE THREAD

**Issue by simogasp** [poparteu/openMVG#69]
* [ ]

**Comment by lcalvet** [comment]
Almost sure that this one is already created.

**Comment by simogasp** [comment]
#63 but that is for CCTag+Sift, first i would like to try a feature only, so that i can see how to generalize and deal with the mixed case

**Comment by lcalvet** [comment]
No, this is exactly #63: "...generic localizer..."

**Comment by lcalvet** [comment]
A single program rig calibration would use the feature type passed in the command line : CCTag, SIFT_CCTAG or SIFT.

**Comment by simogasp** [comment]
yes and I'm talking about localization here. I just want to refactor the existing localization code to deal with more cameras. It's just an intermediate step to get to a generic localizer able to deal with cctag, sift or both of them. And actually, at end, able to calibrate the camera as well, since in the end the algorithms are the same. I will put down the steps in the description so it will be more clear

**Comment by simogasp** [comment]
This is done using localization for each camera. Next step is to use openGV for localize the rig as a generic camera
