### ISSUE TITLE
Using unique IDs throw an error during matching

### ISSUE THREAD

**Issue by caymard** [poparteu/openMVG#71]
I launched a reconstruction with unique IDs for the new Cap Digital dataset. The matching throw an error :
`terminate called after throwing an instance of 'std::out_of_range'`

Script launched for reconstruction :
```shell
~/dev/popart/openMVG/build/install/bin/openMVG_main_SfMInit_ImageListing \
-i /home/popart/datasets/capdigital_2015-11-03/photogrammetry/indoor/ \
-d /home/popart/local/share/openMVG/cameraGenerated.txt \
-o uid/matches/ \
-u 1 \
> log_uid_list.log 2>&1

~/dev/popart/openMVG/build/install/bin/openMVG_main_ComputeFeatures \
-i uid/matches/sfm_data.json \
-o uid/matches \
-m SIFT_CCTAG3 \
> log_uid_feat.log 2>&1

~/dev/popart/openMVG/build/install/bin/openMVG_main_ComputeMatches \
-i uid/matches/sfm_data.json \
-o uid/matches/ \
-n ANNL2 \
> log_uid_match.log 2>&1
```

If I relaunch the pipeline without UIDs everything is fine.

@fcastan @jmelou

**Comment by simogasp** [comment]
what was the problem/solution?

**Comment by caymard** [comment]
I merged the lasts commits of `dev_mikros` into my branch and the problem was solved.

**Comment by simogasp** [comment]
Ok, `voctree_localizer` is now up-to-date with `dev_mikros`, so we should be on the same page now

**Comment by caymard** [comment]
Ok, great. I did a quick merge here but I didn't check that everything works now good. Maybe we can also merge `fix_cctag_related` into `dev_mikros` ? @lcalvet

**Comment by simogasp** [comment]
I have still to fix a couple of things in that one. There are 2 WIP PRs for `dev_mikros` <- `voctree_localizer` <-`fix_cctag_related`
