### ISSUE TITLE
[software] Script for .feat/.desc backcompatibility

### ISSUE THREAD

**Issue by simogasp** [poparteu/openMVG#72]
Since the introduction of UID for the view, .feat/.desc files are now named using the ID of the view (whether the UID are used or not) instead of the image name. For backcompatibility purpose a script is needed to rename the old  .feat/.desc into the new naming system:
The script 
* takes as input a sfmdata file and a directory where .feat/.desc are (usually `matches`)
* for each view in the sfmdata, look in the directory for the `imageName.{feat,desc}`
* rename the file as `viewID.{feat,desc}`

**Comment by pmoulon** [comment]
can be done by using symbolic links over the existing features ;-)
