### ISSUE TITLE
[dataio] Handle unlocalized camera and Maya keyframes with the Alembic animated camera

### ISSUE THREAD

**Issue by caymard** [poparteu/openMVG#85]
Since the animated camera has been introduced in OpenMVG for the localization part, some enhancements need to be done to improve its usage :
- Change the keyframe system to an usable keyframe for Maya. Actually the animated camera has a Alembic node connected to the time, and it streams values to the camera according to the current scene time.
- Handle situations when the camera is not localized. Actually if there is no localization success for an image, the localizer register the new camera position at origin (R = identity and t = [ 0 0 0 ]). A more convenience way is to not register new position (i.e new keyframe) and to let the camera at its previous position (i.e the last position that localizer found)

- [x] keyframe system
- [x] unlocalized camera

**Comment by caymard** [comment]
From what I saw on internet,it is not possible to have keyframes from an Alembic importation. The only way we (maybe) have is a Maya script.

**Comment by fabiencastan** [comment]
Yes, I also think that it is not possible...
Yes, we can do the maya script because in all case, we have to setup the image plane, etc.

**Comment by caymard** [comment]
OK.
Btw, where will I push maya scripts for image plane and so ?

**Comment by simogasp** [comment]
finished?

**Comment by caymard** [comment]
Pull request waiting for merge : https://github.com/poparteu/openMVG/pull/90

**Comment by simogasp** [comment]
keyframe system is implemented? can I close this then?

**Comment by caymard** [comment]
Yep
