### ISSUE TITLE
[bug] TEST(matching_image_collection, contiguousWithOverlap) fails

### ISSUE THREAD

**Issue by simogasp** [poparteu/openMVG#89]
On clang it fails at inside the function `contiguousWithOverlap ` apparently because `std::advance()` goes beyond the `.end()` of the container `Views`
```c++
  sfm::Views::const_iterator itB = itA;
    std::advance(itB, 1);
    sfm::Views::const_iterator itBEnd = itA;
    std::advance(itBEnd, 1 + overlapSize);    <-- seg fault if itBEnd goes beyond view.end()
```

One possible solution is to check before doing advance(), something like
```c++
   sfm::Views::const_iterator itB = itA;
    std::advance(itB, 1);
    sfm::Views::const_iterator itBEnd = itA;
    if(std::distance(itBEnd, views.end()) < 1 + overlapSize)
      break;
    std::advance(itBEnd, 1 + overlapSize);
```

On the other hand, the code on the original develop branch is much simpler, https://github.com/openMVG/openMVG/blob/develop/src/openMVG/matching_image_collection/Pair_Builder.hpp#L32
I don't know if we can use something like that or not

**Comment by fabiencastan** [comment]
The develop branch only creates a list of indexes.
The new code support range computation (to parallelize on renderfarm) & use the input views instead of indexes (allows to use UID or all kind of input sfm_data).

**Comment by simogasp** [comment]
Yes, but still I think we should take care of that `advance()`
