### ISSUE TITLE
[calibration] Add checkerboard calibration application

### ISSUE THREAD

**Issue by fabiencastan** [poparteu/openMVG#9]
- based on OpenCV
- choose a file format for the calibration result

**Comment by simogasp** [comment]
there is an app here 
https://github.com/poparteu/cameraLocalization/blob/dev/applications/ocvtools/calibration.cpp
which is based on a OCV sample that support live (webcam) and manual acquisition of the frames.
For the file format, it uses yet another format YAML which is supported natively by OCV for serialization. maybe there's a way to export JSON instead

**Comment by simogasp** [comment]
Done in popart_demo https://github.com/poparteu/openMVG/commit/51ade9510179530e68a4a88eafc631fbd32600e1
