### ISSUE TITLE
Clean and organize logs in openMVG

### ISSUE THREAD

**Issue by caymard** [poparteu/openMVG#97]
With @simogasp and @fcastan we thought that it will be a great idea to clean and organize logs in openMVG. During tests we have to see/save a lot of debug informations, and when we run the localization for example, we want a more silent trace.

[boostlog](http://www.boost.org/doc/libs/1_60_0/libs/log/doc/html/index.html) seems to be a good client. There is a macro where you can specifiy the level of a log (error, fatal, warning, info, debug, etc) and another to specify which levels you want to print.

We can replace the macro `BOOST_LOG_TRIVIAL(level) << "my text";` by `POPART_LOG_LEVEL("my text");` to be close to the actual log system (`POPART_COUT("my_text");`).

Any suggestions are welcome.

**Comment by pmoulon** [comment]
boostlog seems similar to google-glog.
There is also easyloggingpp https://github.com/easylogging/easyloggingpp

**Comment by fabiencastan** [comment]
@caymard Status?
Can be put into PR?

**Comment by simogasp** [comment]
I doubt it as it is quite old, it needs to be update with a recent develop at least.
The other thing is that `glog` may be a better choice as *in theory* it can grab the logs from ceres as well. Ceres already uses glog (as option), if we also use glog we can collect Ceres' log in ours (not 100% sure but also @nrondaud was thinking it is possible when we discussed about it). Of course this will add a (yet) new dependency

**Comment by simogasp** [comment]
In case, for glog, we can just use this branch where all the `cout/cerr` are replaced by OPENMVG_COUT, add the dependency to cmake, modify the logger.h accordingly, and add the initialization (`google::InitGoogleLogging(argv[0])`) to each binary in `./software/`

**Comment by pmoulon** [comment]
If you plan that I think it would be valuable to use OPENMG_COUT and OPENMVG_CERR. Since if you modifiy an error message to a standard message, you change the library behavior.
Or we could consider to use OPENMVG_LOG_INFO, OPENMVG_LOG_WARNING, OPENMVG_LOG_ERROR

**Comment by simogasp** [comment]
please check the [logger.hpp](https://github.com/poparteu/openMVG/blob/126b38726bdc6ad80de6e3da8675c3e7c3d31061/src/openMVG/logger.hpp)
For now we have `OPENMG_COUT` and `OPENMVG_CERR` that replaces our old `POPART_*` and redefine it in terms of boost logging. Also we redefined cout/cerr into `OPENMVG_*` **only** for the popart new contribution parts (voctree, localizers etc) that were not already defined as macros, we haven't change anything in the library yet.
For sure we can consider what you propose, INFO/WARNING/ERROR as different levels of logging, it think it should be enough. Maybe we can add DEBUG for messages that are needed just for degugging issues that the user might not be interested in.

Then we just need to go through all the cout/cerr of the library and replace accordingly.

**Comment by simogasp** [comment]
@pmoulon what do you think?

**Comment by pmoulon** [comment]
@simogasp 
I think that ```OPENMVG_* (INFO/WARNING/ERROR)``` would be fine.
Adding debug is a good idea too.

According the file logger.hpp I woud like to suggest the following changes:
```
// Add licence header, publish code without a licence means that you do a public domain contribution

#pragma once

#ifdef OPENVMG_USE_BOOST_LOG // replace popart specific LOG_BOOST_POPART_COUT
// Defines simple logging macros for the BOOST based log
#define BOOST_LOG_DYN_LINK 1
#include <boost/log/trivial.hpp>
#define OPENMVG_COUT(x) BOOST_LOG_TRIVIAL(info) << x
#define OPENMVG_CERR(x) BOOST_LOG_TRIVIAL(error) << x
#define OPENMVG_COUT_DEBUG(x) BOOST_LOG_TRIVIAL(debug) << x
#else
#define OPENMVG_COUT(x) // do we must add here std::cout << x
#define OPENMVG_CERR(x) // do we must add here std::cerr << x
#define OPENMVG_COUT_DEBUG(x) // do we must add here std::cout << x
// One day we could consider adding a Glog based output if needed
#endif
```

**Comment by simogasp** [comment]
The headers are missing everywhere in our new files, maybe we can do it in a dedicated issue.

The idea of `logger.hpp` was to be able to suppress all the messages, I don't know if it is still a need (it was back then), that's why the `#defines` were empty. The idea was to have a cmake variable to enable/disable (mute) logging. If this is stil valid we can do something like:

```c++
#ifdef OPENVMG_ENABLE_LOGGING  // by default true

#if OPENMVG_USE_GLOG // can be set in cmake
// here we put the definitions of OPENMVG_* in terms of glog
#define OPENMVG_COUT(x) glog....
....
#elif OPENMVG_USE_BOOSTLOG
// all the boost stuff
#define BOOST_LOG_DYN_LINK 1
#include <boost/log/trivial.hpp>
#define OPENMVG_COUT(x) BOOST_LOG_TRIVIAL(info) << x
...
#else
// define as a simple cout/cerr
#define OPENMVG_COUT(x) std::cout << x
...
#endif 

#else // OPENVMG_ENABLE_LOGGING
// empty definition
#define OPENMVG_COUT(x) 
#define OPENMVG_CERR(x)
#define OPENMVG_COUT_DEBUG(x) 
#endif
```

This way the user has the choice of using boost, glog or the std output as logging, as well as the choice of suppress the logging. The latter can be achieved also with boost and glog by setting the logging level to 0 but not for the std output. Of course `CMakeLists` must be change to manage all the cases and options.
